<?php
// Demo-ready category and product data used for local deployment without a seeded database.
$categories = [
    ['id' => 1, 'slug' => 'flours', 'name' => 'Flours', 'description' => 'Stone-ground staples for everyday cooking.'],
    ['id' => 2, 'slug' => 'non-dairy', 'name' => 'Non-Dairy', 'description' => 'Plant-powered essentials for modern kitchens.'],
];

$products = [
    [
        'id' => 1,
        'category' => 'flours',
        'name' => 'Wheat Flour',
        'price' => 120,
        'unit' => '5 kg',
        'badge' => 'Best Seller',
        'image' => 'https://images.unsplash.com/photo-1603048719539-9ecb4d57eaf7?auto=format&fit=crop&w=900&q=80',
        'description' => 'Freshly milled wheat flour with balanced texture for chapati, bread, and baking.',
    ],
    [
        'id' => 2,
        'category' => 'flours',
        'name' => 'Pea Flour',
        'price' => 140,
        'unit' => '2 kg',
        'badge' => 'Protein Rich',
        'image' => 'https://images.unsplash.com/photo-1515543904379-3d757afe72e7?auto=format&fit=crop&w=900&q=80',
        'description' => 'Nutritious pea flour suited for gluten-aware recipes and savory snacks.',
    ],
    [
        'id' => 3,
        'category' => 'flours',
        'name' => 'Gram Flour',
        'price' => 110,
        'unit' => '2 kg',
        'badge' => 'Kitchen Essential',
        'image' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=900&q=80',
        'description' => 'Classic besan for pakoras, laddoos, chilla, and regional specialties.',
    ],
    [
        'id' => 4,
        'category' => 'flours',
        'name' => 'Urad Flour',
        'price' => 155,
        'unit' => '1 kg',
        'badge' => 'Premium',
        'image' => 'https://images.unsplash.com/photo-1615485291234-9fbc9b1b9aaa?auto=format&fit=crop&w=900&q=80',
        'description' => 'Smooth urad flour that works beautifully for papad, dosa mixes, and batters.',
    ],
    [
        'id' => 5,
        'category' => 'flours',
        'name' => 'Barley Flour',
        'price' => 130,
        'unit' => '2 kg',
        'badge' => 'Fiber Boost',
        'image' => 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=900&q=80',
        'description' => 'Wholesome barley flour ideal for healthy rotis, cookies, and porridges.',
    ],
    [
        'id' => 6,
        'category' => 'non-dairy',
        'name' => 'Soy Milk',
        'price' => 85,
        'unit' => '1 L',
        'badge' => 'Dairy-Free',
        'image' => 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=900&q=80',
        'description' => 'Creamy soy milk with a clean finish for cereals, coffee, and smoothies.',
    ],
    [
        'id' => 7,
        'category' => 'non-dairy',
        'name' => 'Flavored Milk',
        'price' => 95,
        'unit' => '750 ml',
        'badge' => '5 Flavors',
        'image' => 'https://images.unsplash.com/photo-1514996937319-344454492b37?auto=format&fit=crop&w=900&q=80',
        'description' => 'Enjoy Banana, Kesar Almond, Strawberry, Mango, and Sweet soy-based flavored milk.',
    ],
    [
        'id' => 8,
        'category' => 'non-dairy',
        'name' => 'Soy Tofu',
        'price' => 90,
        'unit' => '400 g',
        'badge' => 'High Protein',
        'image' => 'https://images.unsplash.com/photo-1603048297172-c92544798d5a?auto=format&fit=crop&w=900&q=80',
        'description' => 'Fresh soy tofu with a tender bite for curries, salads, grills, and wraps.',
    ],
    [
        'id' => 9,
        'category' => 'non-dairy',
        'name' => 'Masala Tofu',
        'price' => 110,
        'unit' => '400 g',
        'badge' => 'Ready to Cook',
        'image' => 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=900&q=80',
        'description' => 'Spiced tofu cubes marinated for quick stir-fries, rolls, and appetizers.',
    ],
];
